name: Run Test Cases
env:
  CI_SERVER: 1
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Lint
        run: |
          npm version
          npm i --no-save
          npm run lint
  test:
    needs: [ lint ]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 18
          - 20
          - 22
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: 'x64'
      - run: node -p '`karmaLogs=${path.join(os.tmpdir(), `_karma_webpack_*`)}`' >> $GITHUB_ENV
        if: matrix.os != 'windows-latest'
      - run: node -p '`karmaLogs=${path.join(os.tmpdir(), `_karma_webpack_*`)}`' >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'
      - name: Test
        run: |
          npm version
          npm i --no-save
          npm t
        env:
          FORCE_COLOR: 2
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs-(${{ matrix.os }}-${{ matrix.node }})
          path: ${{ env.karmaLogs }}
          retention-days: 7
